name: 03 Workflows, Jobs, and Steps

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is Step 1.1 of Job 1"
      - run: echo "This is Step 1.2 of Job 1"
      - run: echo "This is Step 1.3 of Job 1"
      - run: echo "This is Step 1.4 of Job 1"

  job-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is Step 2.1 of Job 2"
      - run: echo "Multiple jobs can run in parallel!"

  job-3:
    runs-on: ubuntu-latest
    needs:
      - job-1
      - job-2
    steps:
      - run: echo "This is Step 3.1 of Job 3"
      - run: echo "They can also depend on one another."

  job-4:
    runs-on: ubuntu-latest
    needs: [job-2, job-3]
    steps:
      - run: echo "This is Step 4.1 of Job 4"
      - run: echo "Job 4 starts only after Job 3 is complete."
