name: 01-02 Step Types

on:
  workflow_dispatch:

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from an inline bash script in a GitHub Actions workflow!"

  say-hello-inline-python:
    runs-on: ubuntu-latest
    steps:
      - run: print("Hello from an inline Python script in a GitHub Actions workflow!")
        shell: python

  say-hello-uses-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'from an action in the Github action marketplace! ðŸ‘‹'
