name: 02-02 Artifacts

on:
  workflow_dispatch:

jobs:
  artifact-producer:
    runs-on: ubuntu-latest
    steps:
      - name: Create a file to upload as an artifact
        run: |
          echo "This is a sample artifact file." > sample-artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-artifact
          path: sample-artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  artifact-consumer:
    runs-on: ubuntu-latest
    needs: artifact-producer
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sample-artifact

      - name: Cat the artifact file
        run: cat sample-artifact.txt
